### ISSUE TITLE
Dependency installation failed

### ISSUE THREAD

**Issue by sunbod** [bRAGAI/bRAG-langchain#4]
My system is ubuntu24.04 and kernel is 6.8.0-48-generic
pip install pyobjc==9.0.1
-----
Collecting pyobjc==9.0.1
  Using cached pyobjc-9.0.1-py3-none-any.whl.metadata (25 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3367, in _dep_map
    return self.__dep_map
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3147, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 186, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 232, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 303, in __init__
    super().__init__(
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 158, in __init__
    self.dist = self._prepare()
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 247, in _prepare
    self._check_metadata_consistency(dist)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 229, in _check_metadata_consistency
    list(dist.iter_dependencies(list(dist.iter_provided_extras())))
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 250, in iter_provided_extras
    return self._extra_mapping.keys()
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_internal/metadata/pkg_resources.py", line 94, in _extra_mapping
    canonicalize_name(extra): extra for extra in self._dist.extras
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3323, in extras
    return [dep for dep in self._dep_map if dep]
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3369, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3386, in _compute_dependencies
    common = types.MappingProxyType(dict.fromkeys(reqs_for_extra(None)))
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/pkg_resources/__init__.py", line 3383, in reqs_for_extra
    if not req.marker or req.marker.evaluate({'extra': extra}):
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 325, in evaluate
    return _evaluate_markers(self._markers, current_environment)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 225, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/markers.py", line 183, in _eval_op
    return spec.contains(lhs, prereleases=True)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 552, in contains
    normalized_item = _coerce_version(item)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/specifiers.py", line 28, in _coerce_version
    version = Version(version)
  File "/home/sunbo/anaconda3/envs/rag2/lib/python3.10/site-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '6.8.0-48-generic'

**Comment by tahababou12** [comment]
Hey @sunbod!

1. Did you create your virtual environment first before running `pip install -r requirements.txt` ?
2. Which python version are you using?

If yes, run `which python` to make sure that you are using python from your virtual env

**Comment by sunbod** [comment]
> Hey @sunbod!
> 
> 1. Did you create your virtual environment first before running `pip install -r requirements.txt` ?
> 2. Which python version are you using?
> 
> If yes, run `which python` to make sure that you are using python from your virtual env

Thanks for your reply,My virtual environment is Python 3.11.7 and used conda
```sh
python --version
Python 3.11.7
```

**Comment by tahababou12** [comment]
Can you run `which python` and paste it here?

**Comment by sunbod** [comment]
> Can you run `which python` and paste it here?

sure
```sh
(sunbo) sunbo@sunbo-CV15S:~/Documents/git/private/bRAG-langchain$ conda activate rag
(rag) sunbo@sunbo-CV15S:~/Documents/git/private/bRAG-langchain$ which python
/home/sunbo/anaconda3/envs/rag/bin/python
(rag) sunbo@sunbo-CV15S:~/Documents/git/private/bRAG-langchain$ pip install pyobjc==9.0.1
Collecting pyobjc==9.0.1
  Using cached pyobjc-9.0.1-py3-none-any.whl.metadata (25 kB)
ERROR: Exception:
Traceback (most recent call last):
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 105, in _run_wrapper
    status = _inner_run()
             ^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/cli/base_command.py", line 96, in _inner_run
    return self.run(options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/cli/req_command.py", line 67, in wrapper
    return func(self, options, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/commands/install.py", line 379, in run
    requirement_set = resolver.resolve(
                      ^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 95, in resolve
    result = self._result = resolver.resolve(
                            ^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 546, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 397, in resolve
    self._add_to_criteria(self.state.criteria, r, parent=None)
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _add_to_criteria
    if not criterion.candidates:
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/resolvelib/structs.py", line 156, in __bool__
    return bool(self._sequence)
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 174, in __bool__
    return any(self)
           ^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 162, in <genexpr>
    return (c for c in iterator if id(c) not in self._incompatible_ids)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 53, in _iter_built
    candidate = func()
                ^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 187, in _make_candidate_from_link
    base: Optional[BaseCandidate] = self._make_base_candidate_from_link(
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 233, in _make_base_candidate_from_link
    self._link_candidate_cache[link] = LinkCandidate(
                                       ^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 304, in __init__
    super().__init__(
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 159, in __init__
    self.dist = self._prepare()
                ^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 248, in _prepare
    self._check_metadata_consistency(dist)
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 230, in _check_metadata_consistency
    list(dist.iter_dependencies(list(dist.iter_provided_extras())))
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_dists.py", line 220, in iter_dependencies
    elif any(req.marker.evaluate(context) for context in contexts):
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_internal/metadata/importlib/_dists.py", line 220, in <genexpr>
    elif any(req.marker.evaluate(context) for context in contexts):
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/markers.py", line 325, in evaluate
    return _evaluate_markers(self._markers, current_environment)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/markers.py", line 225, in _evaluate_markers
    groups[-1].append(_eval_op(lhs_value, op, rhs_value))
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/markers.py", line 183, in _eval_op
    return spec.contains(lhs, prereleases=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/specifiers.py", line 552, in contains
    normalized_item = _coerce_version(item)
                      ^^^^^^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/specifiers.py", line 28, in _coerce_version
    version = Version(version)
              ^^^^^^^^^^^^^^^^
  File "/home/sunbo/anaconda3/envs/rag/lib/python3.11/site-packages/pip/_vendor/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
pip._vendor.packaging.version.InvalidVersion: Invalid version: '6.8.0-48-generic'
```

**Comment by jaredzhou** [comment]
really a lot of conflict in dependency, but you can install depency every notebook seperately, that is a lot easier

**Comment by tahababou12** [comment]
This issue has been fixed! 🎉 All dependency installation problems, including the `pyobjc` conflict, are resolved. Please pull the latest changes from the repository and follow the updated instructions in the README to get started smoothly.  

Feel free to open a new ticket if you run into any other issues or have any questions. Thank you for your patience and support while resolving this!
